Ip's are now 0.0.0.0, no need to change them
- hosts-file now comes with 0.0.0.0 as the ip, no need to change it anymore
- add die()
- add error checks to all commands
- add trap statement to remove the tmpfile when exiting
- use long options in commands

diff --git a/hosts_update b/hosts_update
--- a/hosts_update
+++ b/hosts_update
@@ -1,37 +1,32 @@
 #!/bin/bash
 # Script by Wintervenom
 # https://bbs.archlinux.org/viewtopic.php?id=106367
+# Forked from https://github.com/graysky2/hosts-update
 # Modified by schalox
 
-if (( "$(id -u)" != 0 )); then
-    echo "This script must be run as root"
+die() {
+    echo "Error: $@"
     exit 1
-fi
+}
 
-if [[ ! -f /etc/hosts.local ]]; then
-    echo "You need to create /etc/hosts.local containing the hosts you wish to keep!"
-    exit 1
-fi
+(( $(id --user) )) && die "This script must be run as root"
 
-tmpfile="$(mktemp)"
+[[ -f /etc/hosts.local ]] ||
+    die "You need to create /etc/hosts.local containing the hosts you wish to keep!"
 
-curl -s -o "$tmpfile" "http://winhelp2002.mvps.org/hosts.txt"
-if (( $? != 0 )) ; then
-    echo "Failed to download the list"
-    rm -f "$tmpfile"
-    exit 1
-fi
+# Create the tmpfile, delete it when the script exits
+tmpfile="$(mktemp)" || die "Couldn't create the tmpfile"
+trap "rm --force "$tmpfile"" EXIT
 
-# Replace /etc/hosts with /etc/hosts.local
-cat /etc/hosts.local > /etc/hosts
+curl --silent --output "$tmpfile" "http://winhelp2002.mvps.org/hosts.txt" ||
+    die "Failed to download the list"
+
+cp --force /etc/hosts.local /etc/hosts ||
+    die "Couldn't replace /etc/hosts with /etc/hosts.local"
 
 # Delete irrelevant lines and carriage returns,
-# replace every IP address with 0.0.0.0,
 # append tmpfile to /etc/hosts
 awk '/^# \[Start of entries/,/^# \[end of entries/ {
         sub(/\r$/, "")
-        sub(/^([0-9]{1,3}\.){3}[0-9]{1,3}/, "0.0.0.0")
         print
-    }' "$tmpfile" >> /etc/hosts
-
-rm -f "$tmpfile"
+    }' "$tmpfile" >> /etc/hosts || die "Couldn't append to /etc/hosts"
